spring.application.name=DesafioPraticoBackEndJava

# Configuracao do banco PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=M3u@m0r8183282026

# Dialeto e comportamento do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console (opcional, util para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

